# Generated by Django 5.0.1 on 2025-10-12 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент корзины",
                "verbose_name_plural": "Элементы корзины",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        max_length=20,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значение скидки"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действителен с")),
                ("valid_to", models.DateTimeField(verbose_name="Действителен до")),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Лимит использований"
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Использован раз"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("processing", "В обработке"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма товаров"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Стоимость доставки",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Итоговая сумма"
                    ),
                ),
                ("shipping_address", models.JSONField(verbose_name="Адрес доставки")),
                (
                    "billing_address",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Адрес плательщика"
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартная доставка"),
                            ("express", "Экспресс доставка"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Карта"), ("paypal", "PayPal")],
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Трек-номер"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена на момент покупки",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элементы заказа",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("processing", "В обработке"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса заказа",
                "verbose_name_plural": "История статусов заказов",
                "ordering": ["-changed_at"],
            },
        ),
    ]
