# Generated by Django 5.0.1 on 2025-10-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="Получатель"),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("registration", "Регистрация"),
                            ("password_reset", "Восстановление пароля"),
                            ("order_created", "Заказ создан"),
                            ("order_paid", "Заказ оплачен"),
                            ("order_shipped", "Заказ отправлен"),
                            ("order_delivered", "Заказ доставлен"),
                            ("newsletter", "Рассылка"),
                        ],
                        max_length=50,
                        verbose_name="Тип письма",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог Email",
                "verbose_name_plural": "Логи Email",
                "ordering": ["-created_at"],
            },
        ),
    ]
